version: "3.9"

services:

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: rfid
    volumes:
      - mongo_data:/data/db
    networks:
      db_net:
        ipv4_address: 172.18.3.2


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      app_net:
        ipv4_address: 172.18.2.2
      db_net:
        ipv4_address: 172.18.3.3


  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      dmz_net:
        ipv4_address: 172.18.1.2
      app_net:
        ipv4_address: 172.18.2.4


  ansible:
    image: quay.io/ansible/ansible-runner:latest
    container_name: ansible
    volumes:
      - ./ansible:/ansible
    working_dir: /ansible
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - mongo
      - backend
      - frontend
    networks:
      - dmz_net
      - app_net
      - db_net


volumes:
  mongo_data:


networks:

  dmz_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.1.0/24


  app_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.18.2.0/24


  db_net:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.18.3.0/24